app/uk/gov/hmrc/agentmappingfrontend/views/add_code.scala.html
app/uk/gov/hmrc/agentmappingfrontend/views/start.scala.html

"Agent Code" is a GG concept, what we have here are CESA Agent References.

[FD][APB-700] Wording fix

---

app/uk/gov/hmrc/agentmappingfrontend/auth/AuthActions.scala
app/uk/gov/hmrc/agentmappingfrontend/controllers/MappingController.scala
conf/application.conf
it/uk/gov/hmrc/agentmappingfrontend/controllers/BaseControllerISpec.scala
it/uk/gov/hmrc/agentmappingfrontend/controllers/CheckMappingControllerWhitelistingISpec.scala
it/uk/gov/hmrc/agentmappingfrontend/stubs/AuthStub.scala
it/uk/gov/hmrc/agentmappingfrontend/support/EndpointBehaviours.scala
project/FrontendBuild.scala
test/uk/gov/hmrc/agentmappingfrontend/auth/AuthActionsSpec.scala
test/uk/gov/hmrc/agentmappingfrontend/auth/TestAuthActions.scala
test/uk/gov/hmrc/agentmappingfrontend/controllers/AuthActionsSpec.scala
test/uk/gov/hmrc/agentmappingfrontend/controllers/MappingControllerSpec.scala
test/uk/gov/hmrc/agentmappingfrontend/support/TestPasscodeAuthenticationProvider.scala
test/uk/gov/hmrc/agentmappingfrontend/support/TestPasscodeVerificationConfig.scala

This reverts commit b2bfa5af9037c4809f0188349bec394743f6572d.

[DK][APB-828] Add passcode authentication

---

app/uk/gov/hmrc/agentmappingfrontend/views/add_code.scala.html
app/uk/gov/hmrc/agentmappingfrontend/views/complete.scala.html
app/uk/gov/hmrc/agentmappingfrontend/views/start.scala.html

Content updated to match latest provided by Charlie Ivens

[BW]-[APB-844]-Latest content added

---

app/uk/gov/hmrc/agentmappingfrontend/controllers/MappingController.scala
app/uk/gov/hmrc/agentmappingfrontend/views/add_code.scala.html
it/uk/gov/hmrc/agentmappingfrontend/controllers/MappingControllerISpec.scala

Error styles added to error message and content updated as requested.

[BW][Apb 844]

---

app/uk/gov/hmrc/agentmappingfrontend/views/add_code.scala.html

closing div moved to correct layout issue introduced in last push.

[BW][APB-844]

---

app/uk/gov/hmrc/agentmappingfrontend/config/frontendAppConfig.scala
app/uk/gov/hmrc/agentmappingfrontend/controllers/SignedOutController.scala
app/uk/gov/hmrc/agentmappingfrontend/views/already_mapped.scala.html
app/uk/gov/hmrc/agentmappingfrontend/views/complete.scala.html
app/uk/gov/hmrc/agentmappingfrontend/views/not_enrolled.scala.html
conf/app.routes
conf/application.conf
conf/messages
it/uk/gov/hmrc/agentmappingfrontend/controllers/MappingControllerISpec.scala
it/uk/gov/hmrc/agentmappingfrontend/controllers/SignOutControllerISpec.scala

to the mapping complete page. This will sign the user out and redirect them
to the add-code page. The sign out button will now sign the user out
and redirect them to the mapping start page

[APB-896][LS] Implemented sign out and redirect

---

app/uk/gov/hmrc/agentmappingfrontend/connectors/MappingConnector.scala
it/uk/gov/hmrc/agentmappingfrontend/stubs/MappingStubs.scala

[APB-1245][PT]: Corrected Delete Call url

---

app/uk/gov/hmrc/agentmappingfrontend/auth/AuthActions.scala
app/uk/gov/hmrc/agentmappingfrontend/controllers/MappingController.scala
app/uk/gov/hmrc/agentmappingfrontend/views/start.scala.html
conf/app.routes
it/uk/gov/hmrc/agentmappingfrontend/controllers/MappingControllerISpec.scala
it/uk/gov/hmrc/agentmappingfrontend/stubs/AuthStub.scala
it/uk/gov/hmrc/agentmappingfrontend/support/EndpointBehaviours.scala
test/uk/gov/hmrc/agentmappingfrontend/auth/AuthActionsSpec.scala

Updated unit tests and it tests with submit start auth checks

[APB-1508][LS,PT] Added auth check on start of mapping for HMRC-AS-AGENT

---

app/uk/gov/hmrc/agentmappingfrontend/auth/AuthActions.scala
app/uk/gov/hmrc/agentmappingfrontend/controllers/MappingController.scala
app/uk/gov/hmrc/agentmappingfrontend/views/start.scala.html
conf/messages
it/uk/gov/hmrc/agentmappingfrontend/controllers/AuthActionsSpec.scala
it/uk/gov/hmrc/agentmappingfrontend/controllers/MappingControllerISpec.scala

[APB-2458][AK] start page dynamic show arn if HMRC-AS-AGENT

---

app/uk/gov/hmrc/agentmappingfrontend/controllers/package.scala
conf/messages
it/uk/gov/hmrc/agentmappingfrontend/controllers/FieldMappingsSpec.scala
it/uk/gov/hmrc/agentmappingfrontend/controllers/MappingControllerISpec.scala
test/uk/gov/hmrc/agentmappingfrontend/controllers/MappingFormSpec.scala

 [APB-2471][AK] UTR error messages update

---

app/ErrorHandler.scala
app/uk/gov/hmrc/agentmappingfrontend/views/error_template.scala.html
app/uk/gov/hmrc/agentmappingfrontend/views/error_template_5xx.scala.html

Allows custom 5xx error page to use main template and have correct styling.

[APB-4374][MP] Extract out new view for custom 5xx error page

---

app/assets/javascripts/am-fe.js
app/assets/javascripts/session-timeout.js
app/uk/gov/hmrc/agentmappingfrontend/controllers/SignedOutController.scala
app/uk/gov/hmrc/agentmappingfrontend/views/govuk_wrapper.scala.html
app/uk/gov/hmrc/agentmappingfrontend/views/main_template.scala.html
app/uk/gov/hmrc/agentmappingfrontend/views/timed_out.scala.html
conf/app.routes
conf/messages

to behave differently whether pop out times out or user manually signs out

[APB-4627][MP] fixing timeout 

---

conf/messages.cy

This is the remaining few messages for the welsh language.

APB-4773 welsh language

---

app/uk/gov/hmrc/agentmappingfrontend/views/complete.scala.html
conf/messages.cy
conf/messages.en
it/uk/gov/hmrc/agentmappingfrontend/controllers/MappingControllerISpec.scala

Is there a task list version of the mapping complete screen in agent-subscription? I couldn't find it

APB-5332 [CS] content update for MTD VAT

---

app/uk/gov/hmrc/agentmappingfrontend/config/frontendAppConfig.scala
app/uk/gov/hmrc/agentmappingfrontend/views/MainTemplate.scala.html
app/uk/gov/hmrc/agentmappingfrontend/views/client_relationships_found.scala.html
app/uk/gov/hmrc/agentmappingfrontend/views/existing_client_relationships.scala.html
app/uk/gov/hmrc/agentmappingfrontend/views/gg_tag.scala.html
app/uk/gov/hmrc/agentmappingfrontend/views/task_list_start.scala.html
conf/application.conf

it took too long to figure out why the `@standardBetaBanner` wouldn't render on it's own haha

APB-5518 [CS] add beta banner

---

app/uk/gov/hmrc/agentmappingfrontend/views/incorrect_account.scala.html

APB-5518 [CS] | fix link position

---

app/uk/gov/hmrc/agentmappingfrontend/views/complete.scala.html
conf/messages.cy
conf/messages.en
it/uk/gov/hmrc/agentmappingfrontend/controllers/MappingControllerISpec.scala

global error & mapping complete page

APB-6256 [CS] remove mtd-vat refs 

---

app/uk/gov/hmrc/agentmappingfrontend/config/frontendAppConfig.scala
app/uk/gov/hmrc/agentmappingfrontend/views/MainTemplate.scala.html
build.sbt
conf/application.conf
project/AppDependencies.scala

See also https://github.com/hmrc/agent-overseas-frontend/pull/68

live [CS] remove beta banner

---

app/uk/gov/hmrc/agentmappingfrontend/views/task_list_start.scala.html
conf/messages.cy
conf/messages.en
it/test/uk/gov/hmrc/agentmappingfrontend/controllers/TaskListMappingControllerISpec.scala

I didn't see any failures in UI tests, perhaps this page isn't visited there

APB-9032 Update task list start page contents

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/modules/_custom.scss
app/uk/gov/hmrc/agentmappingfrontend/controllers/MappingController.scala
app/uk/gov/hmrc/agentmappingfrontend/model/StartMappingForm.scala
app/uk/gov/hmrc/agentmappingfrontend/views/start.scala.html
conf/app.routes
conf/messages.cy
conf/messages.en
it/test/uk/gov/hmrc/agentmappingfrontend/controllers/MappingControllerISpec.scala

Draft until we receive 2 pieces of missing Welsh translation - so will need one more commit...

APB-9311 new ASA start page

---

app/uk/gov/hmrc/agentmappingfrontend/auth/AuthActions.scala
app/uk/gov/hmrc/agentmappingfrontend/config/frontendAppConfig.scala
app/uk/gov/hmrc/agentmappingfrontend/controllers/MappingController.scala
app/uk/gov/hmrc/agentmappingfrontend/controllers/SignedOutController.scala
app/uk/gov/hmrc/agentmappingfrontend/views/MainTemplate.scala.html
app/uk/gov/hmrc/agentmappingfrontend/views/page_not_found.scala.html
app/uk/gov/hmrc/agentmappingfrontend/views/start.scala.html
app/uk/gov/hmrc/agentmappingfrontend/views/start_sign_in_required.scala.html
app/uk/gov/hmrc/agentmappingfrontend/views/timed_out.scala.html
conf/app.routes
conf/application.conf
it/test/uk/gov/hmrc/agentmappingfrontend/controllers/AuthActionsSpec.scala
it/test/uk/gov/hmrc/agentmappingfrontend/controllers/SignOutControllerISpec.scala
project/AppDependencies.scala
project/plugins.sbt

Also we need these config commits merged:
https://github.com/hmrc/app-config-base/pull/12359
https://github.com/hmrc/app-config-qa/pull/25875
https://github.com/hmrc/app-config-staging/pull/17825
https://github.com/hmrc/app-config-production/pull/25991

APB-9617 new sign out and time out

---

app/uk/gov/hmrc/agentmappingfrontend/controllers/MappingController.scala
app/uk/gov/hmrc/agentmappingfrontend/controllers/TaskListMappingController.scala
app/uk/gov/hmrc/agentmappingfrontend/views/existing_client_relationships.scala.html
it/test/uk/gov/hmrc/agentmappingfrontend/controllers/TaskListMappingControllerISpec.scala
project/AppDependencies.scala

Opening as draft - would like to get interaction design acknowledgement that this change is ok

APB-9856 remove unwanted back link
